name: build and release
on: push
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # cacheing
    - name: Cache ~/.local/bin
      uses: actions/cache@v1
      with:
        path: ~/.local/bin/
        key: ${{ runner.os }}-local-bin

    - name: Cache /usr/local/bin/aws
      uses: actions/cache@v1
      with:
        path: /usr/local/bin/aws
        key: ${{ runner.os }}-aws

    - name: path
      run: export PATH="$PATH:~/.local/bin"

    - name: install
      run: bash scripts/install.sh

    - name: build
      run: milkshake-cli sitemap.yaml -c

    - name: release
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: scripts/release.sh `basename ${{ github.ref }}`
