name: cicd

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # cacheing
    - name: Cache ~/.local/bin
      uses: actions/cache@v1
      with:
        path: ~/.local/bin/
        key: ${{ runner.os }}-local-bin

    - name: Cache /usr/local/bin/aws
      uses: actions/cache@v1
      with:
        path: /usr/local/bin/aws
        key: ${{ runner.os }}-aws

    - name: install
      run: |
        mkdir -p $HOME/.local/bin
        export PATH=$PATH:$HOME/.local/bin
        bash scripts/install_terraform.sh
        sleep 1
        bash scripts/install_milkshake.sh
        sleep 1
        bash scripts/install_aws.sh
        sleep 1

    - name: build
      run: |
        milkshake-cli sitemap.yaml -c

    #- name: release
    #  if: github.ref == 'refs/heads/release'
    #  env:
    #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #    AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    #  run: scripts/release.sh
